require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ClientProfilesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # ClientProfile. As you add validations to ClientProfile, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ClientProfilesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all client_profiles as @client_profiles" do
      client_profile = ClientProfile.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:client_profiles)).to eq([client_profile])
    end
  end

  describe "GET #show" do
    it "assigns the requested client_profile as @client_profile" do
      client_profile = ClientProfile.create! valid_attributes
      get :show, params: {id: client_profile.to_param}, session: valid_session
      expect(assigns(:client_profile)).to eq(client_profile)
    end
  end

  describe "GET #new" do
    it "assigns a new client_profile as @client_profile" do
      get :new, params: {}, session: valid_session
      expect(assigns(:client_profile)).to be_a_new(ClientProfile)
    end
  end

  describe "GET #edit" do
    it "assigns the requested client_profile as @client_profile" do
      client_profile = ClientProfile.create! valid_attributes
      get :edit, params: {id: client_profile.to_param}, session: valid_session
      expect(assigns(:client_profile)).to eq(client_profile)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new ClientProfile" do
        expect {
          post :create, params: {client_profile: valid_attributes}, session: valid_session
        }.to change(ClientProfile, :count).by(1)
      end

      it "assigns a newly created client_profile as @client_profile" do
        post :create, params: {client_profile: valid_attributes}, session: valid_session
        expect(assigns(:client_profile)).to be_a(ClientProfile)
        expect(assigns(:client_profile)).to be_persisted
      end

      it "redirects to the created client_profile" do
        post :create, params: {client_profile: valid_attributes}, session: valid_session
        expect(response).to redirect_to(ClientProfile.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved client_profile as @client_profile" do
        post :create, params: {client_profile: invalid_attributes}, session: valid_session
        expect(assigns(:client_profile)).to be_a_new(ClientProfile)
      end

      it "re-renders the 'new' template" do
        post :create, params: {client_profile: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested client_profile" do
        client_profile = ClientProfile.create! valid_attributes
        put :update, params: {id: client_profile.to_param, client_profile: new_attributes}, session: valid_session
        client_profile.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested client_profile as @client_profile" do
        client_profile = ClientProfile.create! valid_attributes
        put :update, params: {id: client_profile.to_param, client_profile: valid_attributes}, session: valid_session
        expect(assigns(:client_profile)).to eq(client_profile)
      end

      it "redirects to the client_profile" do
        client_profile = ClientProfile.create! valid_attributes
        put :update, params: {id: client_profile.to_param, client_profile: valid_attributes}, session: valid_session
        expect(response).to redirect_to(client_profile)
      end
    end

    context "with invalid params" do
      it "assigns the client_profile as @client_profile" do
        client_profile = ClientProfile.create! valid_attributes
        put :update, params: {id: client_profile.to_param, client_profile: invalid_attributes}, session: valid_session
        expect(assigns(:client_profile)).to eq(client_profile)
      end

      it "re-renders the 'edit' template" do
        client_profile = ClientProfile.create! valid_attributes
        put :update, params: {id: client_profile.to_param, client_profile: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested client_profile" do
      client_profile = ClientProfile.create! valid_attributes
      expect {
        delete :destroy, params: {id: client_profile.to_param}, session: valid_session
      }.to change(ClientProfile, :count).by(-1)
    end

    it "redirects to the client_profiles list" do
      client_profile = ClientProfile.create! valid_attributes
      delete :destroy, params: {id: client_profile.to_param}, session: valid_session
      expect(response).to redirect_to(client_profiles_url)
    end
  end

end
